# Generated by Django 5.2 on 2025-05-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresponse',
            name='session_id',
            field=models.CharField(max_length=300),
        ),
    ]
